version: '3'
services:
  redis:
    image: redis
    ports:
      - 6377:6379
    networks:
      - backend

  ab-pgsql:
    platform: linux/arm64
    image: 'postgres' # use latest official postgres version
    ports:
      - '5433:5432'
    env_file:
      - ../envs/.env # configure postgres
    volumes:
      - local-pessl:/var/lib/pessl-pgsql/data # persist data even if container shuts down
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  local-pessl:
