version: '3.1'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    build:
      context: ./
      dockerfile: db.dockerfile
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready
      interval: 1s
      retries: 10
